language: go
go:
  - "1.12"

env:
  - GO111MODULE=on

script:
  - go test -v -race ./service

deploy:
  - provider: script
    skip_cleanup: true
    script: >-
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && curl -sL
      https://git.io/goreleaser | bash
    on:
      tags: true
