version: "3"

services:
  pico:
    image: picostack/pico
    environment:
      HOSTNAME: ${HOSTNAME}
      DEBUG: "1"
      DIRECTORY: "/cache"
      CHECK_INTERVAL: "10s"
      VAULT_ADDR: "https://vault.my.infra.systems"
      VAULT_TOKEN: ${VAULT_TOKEN}
      VAULT_PATH: "a/subdirectory/inside/vault/"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /cache:/cache
  vault:
    image: vault
    command: server -dev
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: 00000000-0000-0000-0000-000000000000
    cap_add:
      - IPC_LOCK
    ports:
      - 8200:8200
