name: wadsworth
version: git
summary: A Git-driven task automation tool
description: The Mister Handy robot of automation!

grade: devel
confinement: devmode

parts:
  wadsworth:
    source: .
    plugin: go
    go-importpath: github.com/Southclaws/wadsworth

apps:
  wadsworth:
    command: wadsworth
