name: Deploy

on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2-beta
        with:
          go-version: 1.14.1
      - uses: actions/checkout@v2
      - run: go get -v -t -d

      - name: Test
        run: go test -v ./...

      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
