name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
      - uses: actions/checkout@v2
      - run: go get -v -t -d

      - name: Test
        run: go test -v ./...
